# Vim keys in copy mode
setw -g mode-keys vi
bind 'v' copy-mode

# Resolves Ctrl-V psmux nvim conflict
set -g paste-detection off

# Mouse
set -g mouse on

# Next window without prefix
bind-key -n ö next-window

# Clean status bar
set -g status-left '#S '
set -g status-right ''
setw -g window-status-format '#I:#W'
setw -g window-status-current-format '#I:#W'

# Transparent status bar
set -g status-style bg=default
setw -g window-status-style bg=default
setw -g window-status-current-style bg=default
