vim.g.mapleader = " "
vim.opt.number = true
vim.opt.cursorline = true
vim.opt.laststatus = 3
vim.opt.showtabline = 0
vim.opt.shiftwidth = 4
vim.opt.scrolloff = 100
vim.opt.clipboard = "unnamedplus"
vim.wo.relativenumber = true
vim.o.cmdheight = 0
vim.o.autoread = true
